/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Malee
 */
public class LoginForm extends javax.swing.JFrame {

     CreateAccount cr1 = new CreateAccount();
     ForgotPass fp1 = new ForgotPass();
     About ab1 = new About();

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        LogIn = new javax.swing.JButton();
        forgotPass = new javax.swing.JButton();
        createAcc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passVisibility = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jOptionPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sri Nandana Osu Sala - Login");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("Webp.net-resizeimage (1).jpg")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Password");

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });

        LogIn.setBackground(new java.awt.Color(51, 102, 255));
        LogIn.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        LogIn.setText("Log In");
        LogIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogIn.setBorderPainted(false);
        LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn.setFocusable(false);
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogInMouseExited(evt);
            }
        });
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        forgotPass.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        forgotPass.setForeground(new java.awt.Color(51, 51, 51));
        forgotPass.setText("Forgot Password?");
        forgotPass.setBorder(null);
        forgotPass.setContentAreaFilled(false);
        forgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPass.setFocusable(false);
        forgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotPassMouseExited(evt);
            }
        });
        forgotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassActionPerformed(evt);
            }
        });

        createAcc.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        createAcc.setForeground(new java.awt.Color(51, 51, 51));
        createAcc.setText("Sign Up");
        createAcc.setBorder(null);
        createAcc.setContentAreaFilled(false);
        createAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAcc.setFocusable(false);
        createAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createAccMouseExited(evt);
            }
        });
        createAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/Webp.net-resizeimage (5).jpg"))); // NOI18N
        jLabel3.setFocusable(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/Webp.net-resizeimage.png"))); // NOI18N

        passVisibility.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/Webp.net-resizeimage (2).png"))); // NOI18N
        passVisibility.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passVisibility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passVisibilityMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passVisibilityMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel5.setText("Sri Nandana Osu Sala");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setText("Log In");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel6))))
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(passVisibility)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(createAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(forgotPass, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passVisibility, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAcc)
                .addGap(18, 18, 18)
                .addComponent(forgotPass)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("Help");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jMenuItem1.setText("Guide ");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jMenuItem2.setText("About");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(461, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forgotPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassMouseEntered
    
        forgotPass.setForeground(new java.awt.Color(255, 102, 102));

    }//GEN-LAST:event_forgotPassMouseEntered

    private void forgotPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassMouseExited
        
        forgotPass.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_forgotPassMouseExited

    private void createAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccMouseEntered
        
        createAcc.setForeground(new java.awt.Color(255, 102, 102));
        
    }//GEN-LAST:event_createAccMouseEntered

    private void createAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccMouseExited
        
        createAcc.setForeground(new java.awt.Color(51, 51, 51));
      
    }//GEN-LAST:event_createAccMouseExited

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
   
        passwordField.setEnabled(true);
        
       if(evt.getKeyChar() == KeyEvent.VK_ENTER){
           
           passwordField.requestFocus();
       } 
  
    }//GEN-LAST:event_usernameFieldKeyPressed

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
      
        if(usernameField.getText().contains(" ")){
            
            passwordField.setEnabled(false);
            JOptionPane.showMessageDialog(this, "<html><body><h4>Username Cannot Contain Whitespace Characters !<br><br><h4><center>Please Try Again.....</center></h4></body></html>.","Error !" ,JOptionPane.ERROR_MESSAGE);
            
        }
        else if(usernameField.getText().isEmpty()){
            
            passwordField.setEnabled(false);
            JOptionPane.showMessageDialog(this, "<html><h3>Username Cannot Be Empty !</h3></html>","Warning !" ,JOptionPane.WARNING_MESSAGE);
            
        }

    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped

        passVisibility.setEnabled(true);
        passVisibility.setIcon(new ImageIcon(getClass().getResource("Webp.net-resizeimage (1).png")));
        
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar()== KeyEvent.VK_DELETE){
            
            if(passwordField.getPassword().length==0){
                
                passVisibility.setIcon(new ImageIcon(getClass().getResource("Webp.net-resizeimage (2).png"))); 
                passVisibility.setEnabled(false);
            }
        }
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            
                LogIn.doClick();
                
        }
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void LogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseEntered
        
        LogIn.setForeground(new java.awt.Color(255, 255, 255));
        
    }//GEN-LAST:event_LogInMouseEntered

    private void LogInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseExited
        
       LogIn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_LogInMouseExited

    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered
        
        jMenu1.setSelected(true);
               
    }//GEN-LAST:event_jMenu1MouseEntered

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
        
        jMenu1.setSelected(false);
        
    }//GEN-LAST:event_jMenu1MouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      
        String html = "<html><body><h1><center>Guideline.</h1>"+"<br><h3>First,You Have to Create an Account as You're the Admin of This System."+"<br>Then You Can Log In to the System Using the Username and the Password,<br>You've Given When Creating the Account.<br><br>Remember to Put a Username and a Password That You Will Remember.<br>If You Forget Your Password, You Can Reset the Password by Referring to 'Forgot Password?' in the Login Form.</h3></center>";
        JOptionPane.showMessageDialog(this, String.format(html),"Message !",JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseEntered
        
        jMenu2.setSelected(true);
        
    }//GEN-LAST:event_jMenu2MouseEntered

    private void jMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseExited
        
        jMenu2.setSelected(false);
        
    }//GEN-LAST:event_jMenu2MouseExited

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        ab1.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        
        System.exit(0);
        
    }//GEN-LAST:event_jMenu2MousePressed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        
        passwordField.setEchoChar((char) 0);
        String pass = new String (passwordField.getPassword());
        passwordField.setEchoChar('*');
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Sri_Nandana","root","iammad_287");
            Statement stmt = (Statement)con.createStatement();
            
             ResultSet result = stmt.executeQuery("SELECT username,password FROM Admin;");
             result.next();

             if(result.getString("Username").equals(usernameField.getText()) && result.getString("Password").equals(pass)){
                 
                 JOptionPane.showMessageDialog(null, "<html><h4>Login Successful !</h4></html>");
                 //Billing bl = new Billing();
                // bl.setVisible(true);
                 dispose();
             }
             
             else{
                 
                 JOptionPane.showMessageDialog(this, "<html><h4>Username or Password is Incorrect !<br><br><center>Please Try Again..</center></h4></html>","Error !",JOptionPane.ERROR_MESSAGE);
             }
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "<html><h4>You Need To Create an Account First !</h4></html>", "Error !",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LogInActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            
        passVisibility.setEnabled(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void passVisibilityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passVisibilityMousePressed

        if(passVisibility.isEnabled()){
        
        passVisibility.setIcon(new ImageIcon(getClass().getResource("Webp.net-resizeimage (3).png")));
        passwordField.setEchoChar((char) 0);
        
        }
    }//GEN-LAST:event_passVisibilityMousePressed

    private void passVisibilityMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passVisibilityMouseReleased
        
        if(passVisibility.isEnabled()){
        passVisibility.setIcon(new ImageIcon(getClass().getResource("Webp.net-resizeimage (1).png")));
        passwordField.setEchoChar('*');
        
        }
        
    }//GEN-LAST:event_passVisibilityMouseReleased

    private void createAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccActionPerformed

        if(cr1.isVisible()){

            JOptionPane.showMessageDialog(this, "<html><h4>'Create an Account' Window is Already in Pending State.</h4></html>","Error !",JOptionPane.ERROR_MESSAGE);
            cr1.requestFocus();
        }
        else{

            cr1.setVisible(true);
        }

    }//GEN-LAST:event_createAccActionPerformed

    private void forgotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassActionPerformed
             
        if(fp1.isVisible()){

            JOptionPane.showMessageDialog(this, "<html><h4>'Forgot Password' Window is Already in Pending State.</h4></html>","Error !",JOptionPane.ERROR_MESSAGE);
            fp1.requestFocus();
        }
        else{

            fp1.setVisible(true);
        }
    }//GEN-LAST:event_forgotPassActionPerformed

   
    
    
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JButton createAcc;
    private javax.swing.JButton forgotPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel passVisibility;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
